parameters:
- name: tag   # tag/version
  default: 'latest'
- name: acrRepo # repo name for the service
  default: ''
- name: dockerfilePath
  default: ''
- name: containerRegistrySvcConn  # acr svc conn
  default: 'acr-svcconn'
- name: buildContext    # build context for docker build, depends on service
  default: '**'
- name: artifact
  default: ''

jobs:
- job: DockerBuild
  steps:
    - task: DownloadPipelineArtifact@2
      displayName: Downloading Artifacts
      inputs:
        buildType: 'current'
        artifactName: '${{ parameters.artifact }}'
        targetPath: '${{ parameters.buildContext }}'

    - task: Docker@2
      displayName: Build docker image
      inputs:
        containerRegistry: ${{ parameters.containerRegistrySvcConn }}      
        command: 'build'
        Dockerfile: '${{ parameters.dockerfilePath }}'
        buildContext: '${{ parameters.buildContext }}'
        repository: '${{ parameters.acrRepo }}'
        tags: '${{ parameters.tag }}'

    - script: |
        docker run --rm -v /var/run/docker.sock:/var/run/docker.sock \
        -v $HOME/Library/Caches:/root/.cache/ aquasec/trivy \
        --format template --template "@contrib/junit.tpl" -o junit-report.xml kubefoundationacr.azurecr.io/${{ parameters.acrRepo }}:${{ parameters.tag }}
        ;ls
      displayName: Aquasec Trivy Container Scan
      
    - task: PublishTestResults@2
      displayName: Publish Scan Results
      inputs:
        testResultsFormat: 'JUnit'
        testResultsFiles: '**/junit-report*.xml'
        failTaskOnFailedTests: false
      condition: 'always()'
    - task: Docker@2
      displayName: Push image to container registry
      inputs:
        containerRegistry: ${{ parameters.containerRegistrySvcConn }}
        repository: '${{ parameters.acrRepo }}'
        command: 'push'
        tags: '${{ parameters.tag }}'

