parameters:
- name: tag
  default: 'latest'
- name: acrRepo
  default: 'kubeinnovationacr.azurecr.io'
- name: dockerfilePath
  default: ''
- name: containerRegistrySvcConn
  default: 'e828e3d4-ef79-4f93-99ef-b9056a2f62b7'

jobs:
- job: DockerBuild
  steps:
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: ${{ parameters.acrRepo }}
        dockerfile: ${{ parameters.dockerfilePath }}
        containerRegistry: ${{ parameters.containerRegistrySvcConn }}
        tags: ${{ parameters.tag }}
