parameters:
- name: tag
  default: 'latest'
- name: acrRepo
  default: ''
- name: dockerfilePath
  default: ''
- name: containerRegistrySvcConn
  default: 'acr-svcconn'
- name: buildContext    # build context for docker build, depends on service
  default: '**'
- name: artifact
  default: ''

jobs:
- job: DockerBuild
  steps:
    - task: DownloadPipelineArtifact@2
        displayName: Downloading Artifacts
        inputs:
          buildType: 'current'
          artifactName: '${{ parameters.artifact }}'
          targetPath: '${{ parameters.buildContext }}'

    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: ${{ parameters.acrRepo }}
        dockerfile: ${{ parameters.dockerfilePath }}
        containerRegistry: ${{ parameters.containerRegistrySvcConn }}
        tags: ${{ parameters.tag }}
        buildContext: ${{ parameters.buildContext }}
