parameters:
- name: tag   # tag/version
  default: 'latest'
- name: acrRepo # repo name for the service
  default: ''
- name: dockerfilePath
  default: ''
- name: containerRegistrySvcConn  # acr svc conn
  default: 'acr-svcconn'
- name: buildContext    # build context for docker build, depends on service
  default: '**'

jobs:
- job: DockerBuild
  steps:
    - checkout: none
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: ${{ parameters.acrRepo }}
        dockerfile: ${{ parameters.dockerfilePath }}
        containerRegistry: ${{ parameters.containerRegistrySvcConn }}
        tags: ${{ parameters.tag }}
        buildContext: ${{ parameters.buildContext }}

