parameters:
- name: tag
  default: 'latest'
- name: acrRepo
  default: ''
- name: kubernetesSvcConn
  default: 'KubeInovAKS'
- name: acrName
  default: 'kubeinnovationacr.azurecr.io'

jobs:
- job: HelmDeploy
  steps:
  - checkout: microservicesdemo
  - task: HelmDeploy@0
    displayName: Update dependencies from requirements.yaml
    inputs:
      kubernetesServiceConnection:  ${{ parameters.kubernetesSvcConn }}
      command: 'dep'
      chartType: 'FilePath'
      chartPath: './deploy/kubernetes/helm-chart/'
      arguments: 'update'

  - task: HelmDeploy@0
    displayName: Deploy microservices demo
    inputs:
      connectionType: 'Kubernetes Service Connection'
      kubernetesServiceConnection:  ${{ parameters.kubernetesSvcConn }}
      command: 'upgrade'
      chartType: 'FilePath'
      chartPath: './deploy/kubernetes/helm-chart/'
      releaseName: 'microservices-demo'
      arguments: |
        --create-namespace

## to do add set image 
