parameters:
<<<<<<< HEAD
- name: tag
  default: 'latest'
- name: acrRepo
  default: ''
- name: kubernetesSvcConn
  default: 'KubeInovAKS'
- name: acrName
  default: 'kubeinnovationacr.azurecr.io'
=======
- name: kubernetesSvcConn # kubernetes svc conn
  default: 'kevaks-svcconn'
- name: serviceName # microservice name (overwriting image.<serviceName> in helm)
  default: ''
- name: image # new deployed image (overwriting the image value in helm)
  default: ''
- name: containerRegistry # container registry (overwriting the registry in helm)
  default: 'kevtestacr.azurecr.io'
>>>>>>> 9b84218a55474a0e7163500c18647580d4014a42

jobs:
- job: HelmDeploy
  steps:
<<<<<<< HEAD
  - checkout: microservicesdemo

  - task: Bash@3
    displayName: Update dependencies in requirements.yaml
=======
  - checkout: microservicesdemo # checks out template yaml in microservices-demo

  - task: Bash@3
    displayName: Downloads dependencies from requirements.yaml
>>>>>>> 9b84218a55474a0e7163500c18647580d4014a42
    inputs:
      targetType: 'inline'
      script: 'helm dependency update ./deploy/kubernetes/helm-chart'
      
  - task: HelmDeploy@0
    displayName: Deploy microservices demo
    inputs:
      connectionType: 'Kubernetes Service Connection'
      kubernetesServiceConnection:  ${{ parameters.kubernetesSvcConn }}
      command: 'upgrade'
      chartType: 'FilePath'
      chartPath: './deploy/kubernetes/helm-chart/'
      releaseName: 'microservices-demo'
<<<<<<< HEAD
      #updateDependency: true
      arguments: >
        --create-namespace

## to do add set image 
=======
      failOnStderr: false # https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/helm-deploy?view=azure-devops#when-using-helm-3-if-systemdebug-is-set-to-true-and-helm-upgrade-is-the-command-being-used-the-pipeline-fails-even-though-the-upgrade-was-successful
      arguments: >
        --create-namespace
        --set images.${{ parameters.serviceName }}=${{ parameters.containerRegistry }}/${{ parameters.image }}
        --reuse-values   

       # make sure we dont reset to default values in helm for other services
>>>>>>> 9b84218a55474a0e7163500c18647580d4014a42
