parameters:
- name: tag
  default: 'latest'
- name: acrRepo
  default: ''
- name: kubernetesSvcConn
  default: 'KubeInovAKS'
- name: acrName
  default: 'kubeinnovationacr.azurecr.io'

jobs:
- job: HelmDeploy
  steps:

  - checkout: microservicesdemo
  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: |
        cd /home/vsts/work/1/s/deploy/kubernetes/helm-chart
        ls

  - task: HelmDeploy@0
    inputs:
      connectionType: 'Kubernetes Service Connection'
      kubernetesServiceConnection:  ${{ parameters.kubernetesSvcConn }}
      namespace: catalogue
      command: 'upgrade'
      chartType: 'FilePath'
      chartPath: './deploy/kubernetes/helm-chart/'
      releaseName: 'catalogue-db'
      arguments: |
        '--create-namespace'

## to do add set image 
