parameters:
- name: tag
  default: 'latest'
- name: acrRepo
  default: ''
- name: dockerfilePath
  default: ''
- name: containerRegistrySvcConn
  default: 'KubeInovACR'
- name: buildContext    # build context for docker build, depends on service
  default: '**'

jobs:
- job: DockerBuild
  steps:
    - task: Maven@3
      displayName: 'Maven: building Java app'
      inputs:
        mavenPomFile: ../pom.xml'
        jdkVersionOption: 1.8
        goals: package

    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: ${{ parameters.acrRepo }}
        dockerfile: ${{ parameters.dockerfilePath }}
        containerRegistry: ${{ parameters.containerRegistrySvcConn }}
        tags: ${{ parameters.tag }}
        buildContext: ${{ parameters.buildContext }}

