# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- none

pool:
  vmImage: 'ubuntu-latest'
     
variables:
  kubernetesSvcConn: 'aks-svcconn'
  # enabled: true  - use top right variables to control
  
steps:
  - task: Bash@3
    displayName: Downloads dependencies from requirements.yaml
    inputs:
      targetType: 'inline'
      script: 'helm dependency update ./deploy/kubernetes/helm-chart'

  - task: HelmDeploy@0
    displayName: Enabling zipkin
    inputs:
      connectionType: 'Kubernetes Service Connection'
      kubernetesServiceConnection: $(kubernetesSvcConn)
      command: 'upgrade'
      namespace: sock-shop
      chartType: 'FilePath'
      chartPath: './deploy/kubernetes/helm-chart/'
      releaseName: 'microservices-demo'
      failOnStderr: false # https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/helm-deploy?view=azure-devops#when-using-helm-3-if-systemdebug-is-set-to-true-and-helm-upgrade-is-the-command-being-used-the-pipeline-fails-even-though-the-upgrade-was-successful
      arguments: >
        --set zipkin.enabled=$(enabled)
        --reuse-values   
