trigger: none
pr: none

variables:  
  # service connection for Kube
  kubernetesSvcConn: 'aks-svcconn'

stages:
- stage: IngressNginxSetup
  displayName: Ingress Setup
  jobs:  
  - job: IngressNginxSetup
    steps:

    - task: HelmDeploy@0
      displayName: Ingress Nginx helm repo
      inputs:
        connectionType: 'Kubernetes Service Connection'
        kubernetesServiceConnection: '$(kubernetesSvcConn)'
        command: 'repo'
        arguments: 'add ingress-nginx https://kubernetes.github.io/ingress-nginx'

    - task: HelmDeploy@0
      displayName: Ingress update/deploy
      inputs:
        connectionType: 'Kubernetes Service Connection'
        kubernetesServiceConnection: '$(kubernetesSvcConn)'
        command: 'upgrade'
        namespace: ingress-nginx
        chartType: 'Name'
        chartName: 'ingress-nginx/ingress-nginx'
        releaseName: 'ingress-nginx'
        arguments: > 
          --create-namespace
#          --post-renderer ./kustomize.sh
