trigger: none
pr: none

variables:  
  # service connection for Kube
  kubernetesSvcConn: 'aks-svcconn'

stages:
- stage: LinkerdSetup
  displayName: Linkerd Setup
  jobs:  
  - job: LinkerdSetup
    steps:
    - task: Bash@3
      displayName: Generate exp date
      inputs:
        targetType: 'inline'
        script: |
          DATE=$(date -d '+8760 hour' +"%Y-%m-%dT%H:%M:%SZ") 
          echo "##vso[task.setvariable variable=exp;]$DATE"

    - task: HelmDeploy@0
      displayName: Linkerd helm repo
      inputs:
        connectionType: 'Kubernetes Service Connection'
        kubernetesServiceConnection: '$(kubernetesSvcConn)'
        command: 'repo'
        arguments: 'add linkerd https://helm.linkerd.io/stable'

    - task: HelmDeploy@0
      displayName: Linkerd update/deploy
      inputs:
        connectionType: 'Kubernetes Service Connection'
        kubernetesServiceConnection: '$(kubernetesSvcConn)'
        command: 'upgrade'
        namespace: linkerd
        chartType: 'Name'
        chartName: 'linkerd/linkerd2'
        releaseName: 'linkerd2'
        arguments: >
          --create-namespace
          --set-file global.identityTrustAnchorsPEM=ca.crt
          --set-file identity.issuer.tls.crtPEM=issuer.crt
          --set-file identity.issuer.tls.keyPEM=issuer.key
          --set identity.issuer.crtExpiry=$(exp)
          --set global.prometheusUrl=http://prometheus-operated.monitoring.svc.cluster.local:9090
          --set global.grafanaUrl=http://monitoring-grafana.monitoring.svc.cluster.local:3000

    - task: Kubernetes@1
      displayName: Annotating sock-shop linkerd injection
      inputs:
        connectionType: 'Kubernetes Service Connection'
        kubernetesServiceEndpoint: $(kubernetesSvcConn)
        command: 'annotate'
        arguments: 'namespace sock-shop linkerd.io/inject=enabled --overwrite'
