# Default values for sock-shop.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
java:
    options: -Xms64m -Xmx128m -XX:PermSize=32m -XX:MaxPermSize=64m -XX:+UseG1GC -Djava.security.egd=file:/dev/urandom
zipkin: 
    enabled:  false
    url: zipkin.sock-shop.svc.cluster.local
frontend:
    replicas: 1
loadtest:
    replicas: 2
    enabled: false
    clients: 5
    hatchrate: 5
    runtime: 2m
ingress:
    host: eykubefoundation.westus2.cloudapp.azure.com
images:
    shipping: weaveworksdemos/shipping:0.4.8
    user: weaveworksdemos/user:0.4.4
    userdb: weaveworksdemos/user-db:0.3.0
    queuemaster: weaveworksdemos/queue-master:0.3.1
    payment: weaveworksdemos/payment:0.4.3
    orders: weaveworksdemos/orders:0.4.7
    loadtest: weaveworksdemos/load-test
    frontend: weaveworksdemos/front-end:0.3.12
    catalogue: weaveworksdemos/catalogue:0.3.5
    cataloguedb: weaveworksdemos/catalogue-db:0.3.0
    carts: weaveworksdemos/carts:0.4.8
namespace: sock-shop