apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: socks-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  tls:
  - hosts:
    - {{ .Values.ingress.host }}
    secretName: letsencrypt-prod
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - path: /
        backend:
          serviceName: front-end
          servicePort: 80
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - path: /monitoring
        backend:
          serviceName: monitoring-grafana
          servicePort: 80
