{{- if .Values.loadtest.enabled }}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: load-test
  labels:
    name: load-test
spec:
  replicas: {{ .Values.loadtest.replicas }}
  template:
    metadata:
      labels:
        name: load-test
    spec:
      containers:
      - name: load-test
        image: {{ .Values.images.loadtest }}
        command: ["/bin/sh"]
        args: ["-c", "while true; do locust --host http://front-end.sock-shop.svc.cluster.local -f /config/locustfile.py --clients {{ .Values.loadtest.clients }} --hatch-rate {{ .Values.loadtest.hatchrate }} --run-time {{ .Values.loadtest.runtime }} --no-web; done"]
{{- end }}