apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: northpointmicroservicesdemo 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: northpointmicroservicesdemo 
    spec:
      containers:
        - name: northpointmicroservicesdemo 
          image: kubeinnovationacr.azurecr.io/northpointmicroservicesdemo
          ports:
          - containerPort: 80