{
 "title": "New row",
 "panels": [
  {
   "title": "Uptime",
   "type": "singlestat",
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "(time() - process_start_time_seconds{job=\"monitoring/prometheus\"})"
    }
   ]
  },
  {
   "title": "Local Storage Memory Series",
   "type": "singlestat",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "prometheus_local_storage_memory_series"
    }
   ]
  },
  {
   "title": "Internal Storage Queue Length",
   "type": "singlestat",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "prometheus_local_storage_indexing_queue_length"
    }
   ]
  }
 ]
}
{
 "title": "New row",
 "panels": [
  {
   "title": "Samples ingested (rate-5m)",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(prometheus_local_storage_ingested_samples_total[5m])",
     "legendFormat": "{{ ` {{ job }} `}}"
    }
   ]
  }
 ]
}
{
 "title": "New row",
 "panels": [
  {
   "title": "Target Scrapes (last 5m)",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(prometheus_target_interval_length_seconds_count[5m])",
     "legendFormat": "{{ ` {{ job }} `}}"
    }
   ]
  },
  {
   "title": "Scrape Duration",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "prometheus_target_interval_length_seconds{quantile!=\"0.01\", quantile!=\"0.05\"}",
     "legendFormat": "{{ ` {{ quantile }} `}} ({{ ` {{ interval }} `}})"
    }
   ]
  }
 ]
}
{
 "title": "New row",
 "panels": [
  {
   "title": "Rule Eval Duration",
   "type": "graph",
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "prometheus_evaluator_duration_milliseconds{quantile!=\"0.01\", quantile!=\"0.05\"}",
     "legendFormat": "{{ ` {{ quantile }} `}}"
    }
   ]
  }
 ]
}
{
 "title": "all pods",
 "panels": [
  {
   "title": "Memory Working Set",
   "type": "singlestat",
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{id=\"/\"}) / sum (machine_memory_bytes) * 100"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "singlestat",
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{id=\"/\",}[1m])) / sum (machine_cpu_cores) * 100"
    }
   ]
  },
  {
   "title": "Filesystem Usage",
   "type": "singlestat",
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(container_fs_usage_bytes{id=\"/\"}) / sum(container_fs_limit_bytes{id=\"/\"}) * 100"
    }
   ]
  },
  {
   "title": "Used",
   "type": "singlestat",
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{id=\"/\"})"
    }
   ]
  },
  {
   "title": "Total",
   "type": "singlestat",
   "format": "bytes",
   "valueName": "current",
   "targets": [
    { "expr": "sum(machine_memory_bytes)" }
   ]
  },
  {
   "title": "Used",
   "type": "singlestat",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{id=\"/\"}[1m]))"
    }
   ]
  },
  {
   "title": "Total",
   "type": "singlestat",
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "sum(machine_cpu_cores)" }
   ]
  },
  {
   "title": "Used",
   "type": "singlestat",
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(container_fs_usage_bytes{id=\"/\"})"
    }
   ]
  },
  {
   "title": "Total",
   "type": "singlestat",
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(container_fs_limit_bytes{id=\"/\"})"
    }
   ]
  },
  {
   "title": "Network",
   "type": "graph",
   "yaxes": [
    { "format": "Bps", "label": "transmit / receive" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total[1m]))",
     "legendFormat": "receive"
    },
    {
     "expr": "- sum(rate(container_network_transmit_bytes_total[1m]))",
     "legendFormat": "transmit"
    }
   ]
  }
 ]
}
{
 "title": "each pod",
 "panels": [
  {
   "title": "CPU Usage",
   "type": "graph",
   "yaxes": [
    { "format": "none", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{image!=\"\",name=~\"^k8s_.*\",namespace=\"sock-shop\"}[1m])) by (pod)",
     "legendFormat": "{{ ` {{ pod_name }} `}}"
    }
   ]
  },
  {
   "title": "Memory Working Set",
   "type": "graph",
   "yaxes": [
    { "format": "bytes", "label": "used" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{image!=\"\",name=~\"^k8s_.*\"}) by (pod_name)",
     "legendFormat": "{{ ` {{ pod_name }} `}}"
    }
   ]
  },
  {
   "title": "Network",
   "type": "graph",
   "yaxes": [
    { "format": "Bps", "label": "transmit / receive" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{image!=\"\",name=~\"^k8s_.*\",}[1m])) by (pod_name)",
     "legendFormat": "{{ ` {{ pod_name }} `}} < in"
    },
    {
     "expr": "- sum (rate (container_network_transmit_bytes_total{image!=\"\",name=~\"^k8s_.*\",}[1m])) by (pod_name)",
     "legendFormat": "{{ ` {{ pod_name }} `}} > out"
    }
   ]
  },
  {
   "title": "Filesystem",
   "type": "graph",
   "yaxes": [
    { "format": "bytes", "label": "used" }
   ],
   "targets": [
    {
     "expr": "sum(container_fs_usage_bytes{image!=\"\",name=~\"^k8s_.*\"}) by (pod_name)",
     "legendFormat": "{{ ` {{ pod_name }} `}}"
    }
   ]
  }
 ]
}
{
 "title": "summary",
 "panels": [
  {
   "title": "Memory",
   "type": "singlestat",
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"sock-shop\"}) / sum(machine_memory_bytes{}) * 100"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "singlestat",
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"sock-shop\"}[1m])) / sum (machine_cpu_cores) * 100"
    }
   ]
  },
  {
   "title": "Used",
   "type": "singlestat",
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"sock-shop\"})"
    }
   ]
  },
  {
   "title": "Total",
   "type": "singlestat",
   "format": "bytes",
   "valueName": "current",
   "targets": [
    { "expr": "sum(machine_memory_bytes)" }
   ]
  },
  {
   "title": "Used",
   "type": "singlestat",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"sock-shop\"}[1m]))"
    }
   ]
  },
  {
   "title": "Total",
   "type": "singlestat",
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "sum(machine_cpu_cores)" }
   ]
  }
 ]
}
{
 "title": "New row",
 "panels": [
  {
   "title": "Memory Working Set",
   "type": "graph",
   "yaxes": [
    { "format": "bytes", "label": "used" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"sock-shop\"}) by (pod_name)",
     "legendFormat": "{{ ` {{ pod_name }} `}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "yaxes": [
    { "format": "none", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"sock-shop\"}[1m])) by (pod_name)",
     "legendFormat": "{{ ` {{ pod_name }} `}}"
    }
   ]
  }
 ]
}
{
 "title": "Catalogue",
 "panels": [
  {
   "title": "Catalogue QPS",
   "type": "graph",
   "yaxes": [
    { "format": "ops", "label": "QPS (1 min)" }
   ],
   "targets": [
    {
     "expr": "sum(rate(request_duration_seconds_count{name=\"catalogue\",status_code=~\"2..\",route!=\"metrics\"}[1m])) * 100",
     "legendFormat": "2xx"
    },
    {
     "expr": "sum(rate(request_duration_seconds_count{name=\"catalogue\",status_code=~\"4.+|5.+\"}[1m])) * 100",
     "legendFormat": "4xx/5xx"
    }
   ]
  },
  {
   "title": "Catalogue Latency",
   "type": "graph",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(request_duration_seconds_bucket{name=\"catalogue\"}[1m])) by (name, le))",
     "legendFormat": "99th quantile"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(request_duration_seconds_bucket{name=\"catalogue\"}[1m])) by (name, le))",
     "legendFormat": "50th quantile"
    },
    {
     "expr": "sum(rate(request_duration_seconds_sum{name=\"catalogue\"}[1m])) / sum(rate(request_duration_seconds_count{name=\"catalogue\"}[1m]))",
     "legendFormat": "mean"
    }
   ]
  }
 ]
}
{
 "title": "Cart",
 "panels": [
  {
   "title": "Cart QPS",
   "type": "graph",
   "yaxes": [
    { "format": "ops", "label": "QPS (1 min)" }
   ],
   "targets": [
    {
     "expr": "sum(rate(request_duration_seconds_count{name=\"carts\",status_code=~\"2..\",route!=\"metrics\"}[1m])) * 100",
     "legendFormat": "2xx"
    },
    {
     "expr": "sum(rate(request_duration_seconds_count{name=\"carts\",status_code=~\"4.+|5.+\"}[1m])) * 100",
     "legendFormat": "4xx/5xx"
    }
   ]
  },
  {
   "title": "Cart Latency",
   "type": "graph",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(request_duration_seconds_bucket{name=\"carts\"}[1m])) by (name, le))",
     "legendFormat": "99th quantile"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(request_duration_seconds_bucket{name=\"carts\"}[1m])) by (name, le))",
     "legendFormat": "50th quantile"
    },
    {
     "expr": "sum(rate(request_duration_seconds_sum{name=\"carts\"}[1m])) / sum(rate(request_duration_seconds_count{name=\"carts\"}[1m]))",
     "legendFormat": "mean"
    }
   ]
  }
 ]
}
{
 "title": "Orders",
 "panels": [
  {
   "title": "Orders QPS",
   "type": "graph",
   "yaxes": [
    { "format": "ops", "label": "QPS (1 min)" }
   ],
   "targets": [
    {
     "expr": "sum(rate(request_duration_seconds_count{name=\"orders\",status_code=~\"2..\",route!=\"metrics\"}[1m])) * 100",
     "legendFormat": "2xx"
    },
    {
     "expr": "sum(rate(request_duration_seconds_count{name=\"orders\",status_code=~\"4.+|5.+\"}[1m])) * 100",
     "legendFormat": "4xx/5xx"
    }
   ]
  },
  {
   "title": "Orders Latency",
   "type": "graph",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(request_duration_seconds_bucket{name=\"orders\"}[1m])) by (name, le))",
     "legendFormat": "99th quantile"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(request_duration_seconds_bucket{name=\"orders\"}[1m])) by (name, le))",
     "legendFormat": "50th quantile"
    },
    {
     "expr": "sum(rate(request_duration_seconds_sum{name=\"orders\"}[1m])) / sum(rate(request_duration_seconds_count{name=\"orders\"}[1m]))",
     "legendFormat": "mean"
    }
   ]
  }
 ]
}
{
 "title": "Payment",
 "panels": [
  {
   "title": "Payment QPS",
   "type": "graph",
   "yaxes": [
    { "format": "ops", "label": "QPS (1 min)" }
   ],
   "targets": [
    {
     "expr": "sum(rate(request_duration_seconds_count{name=\"payment\",status_code=~\"2..\",route!=\"metrics\"}[1m])) * 100",
     "legendFormat": "2xx"
    },
    {
     "expr": "sum(rate(request_duration_seconds_count{name=\"payment\",status_code=~\"4.+|5.+\"}[1m])) * 100",
     "legendFormat": "4xx/5xx"
    }
   ]
  },
  {
   "title": "Payment Latency",
   "type": "graph",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(request_duration_seconds_bucket{name=\"payment\"}[1m])) by (name, le))",
     "legendFormat": "99th quantile"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(request_duration_seconds_bucket{name=\"payment\"}[1m])) by (name, le))",
     "legendFormat": "50th quantile"
    },
    {
     "expr": "sum(rate(request_duration_seconds_sum{name=\"payment\"}[1m])) / sum(rate(request_duration_seconds_count{name=\"payment\"}[1m]))",
     "legendFormat": "mean"
    }
   ]
  }
 ]
}
{
 "title": "Shipping",
 "panels": [
  {
   "title": "Shipping QPS",
   "type": "graph",
   "yaxes": [
    { "format": "ops", "label": "QPS (1 min)" }
   ],
   "targets": [
    {
     "expr": "sum(rate(request_duration_seconds_count{name=\"shipping\",status_code=~\"2..\",route!=\"metrics\"}[1m])) * 100",
     "legendFormat": "2xx"
    },
    {
     "expr": "sum(rate(request_duration_seconds_count{name=\"shipping\",status_code=~\"4.+|5.+\"}[1m])) * 100",
     "legendFormat": "4xx/5xx"
    }
   ]
  },
  {
   "title": "Shipping Latency",
   "type": "graph",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(request_duration_seconds_bucket{name=\"shipping\"}[1m])) by (name, le))",
     "legendFormat": "99th quantile"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(request_duration_seconds_bucket{name=\"shipping\"}[1m])) by (name, le))",
     "legendFormat": "50th quantile"
    },
    {
     "expr": "sum(rate(request_duration_seconds_sum{name=\"shipping\"}[1m])) / sum(rate(request_duration_seconds_count{name=\"shipping\"}[1m]))",
     "legendFormat": "mean"
    }
   ]
  }
 ]
}
{
 "title": "User",
 "panels": [
  {
   "title": "User QPS",
   "type": "graph",
   "yaxes": [
    { "format": "ops", "label": "QPS (1 min)" }
   ],
   "targets": [
    {
     "expr": "sum(rate(request_duration_seconds_count{name=\"user\",status_code=~\"2..\",route!=\"metrics\"}[1m])) * 100",
     "legendFormat": "2xx"
    },
    {
     "expr": "sum(rate(request_duration_seconds_count{name=\"user\",status_code=~\"4.+|5.+\"}[1m])) * 100",
     "legendFormat": "4xx/5xx"
    }
   ]
  },
  {
   "title": "User Latency",
   "type": "graph",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(request_duration_seconds_bucket{name=\"user\"}[1m])) by (name, le))",
     "legendFormat": "99th quantile"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(request_duration_seconds_bucket{name=\"user\"}[1m])) by (name, le))",
     "legendFormat": "50th quantile"
    },
    {
     "expr": "sum(rate(request_duration_seconds_sum{name=\"user\"}[1m])) / sum(rate(request_duration_seconds_count{name=\"user\"}[1m]))",
     "legendFormat": "mean"
    }
   ]
  }
 ]
}
{
 "title": "Front End",
 "panels": [
  {
   "title": "Front End QPS",
   "type": "graph",
   "yaxes": [
    { "format": "ops", "label": "QPS (1 min)" }
   ],
   "targets": [
    {
     "expr": "sum(rate(request_duration_seconds_count{name=\"front-end\",status_code=~\"2..\",route!=\"metrics\"}[1m])) * 100",
     "legendFormat": "2xx"
    },
    {
     "expr": "sum(rate(request_duration_seconds_count{name=\"front-end\",status_code=~\"4.+|5.+\"}[1m])) * 100",
     "legendFormat": "4xx/5xx"
    }
   ]
  },
  {
   "title": "Front End Latency",
   "type": "graph",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(request_duration_seconds_bucket{name=\"front-end\"}[1m])) by (name, le))",
     "legendFormat": "99th quantile"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(request_duration_seconds_bucket{name=\"front-end\"}[1m])) by (name, le))",
     "legendFormat": "50th quantile"
    },
    {
     "expr": "sum(rate(request_duration_seconds_sum{name=\"front-end\"}[1m])) / sum(rate(request_duration_seconds_count{name=\"front-end\"}[1m]))",
     "legendFormat": "mean"
    }
   ]
  }
 ]
}